apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}-service
spec:
  selector:
    app: {{ .Values.app }}
  ports:
  - protocol: {{ .Values.protocol }}
    port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
