apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/immich-app/immich-charts
    targetRevision: HEAD
    path: charts/immich
  helm:
    valueFiles:
      - Helm-charts/immich/immich-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
