apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://immich-app.github.io/immich-charts
      targetRevision: 0.9.3
      chart: immich  # <- Fixed: use just the chart name
      helm:
        releaseName: immich
        valueFiles:
          - $values/Helm-charts/immich/immich-values.yaml  # This is from your second repo

    - repoURL: https://github.com/RJ598/kubecluster
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
