apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd  # Argo CD's namespace
spec:
  project: default

  source:
    repoURL: https://github.com/RJ598/kubecluster  # 🔁 Replace with your repo
    targetRevision: main  # or a tag/branch
    path: Applications/postgress    # 🔁 Path inside the repo to your YAML files

  destination:
    server: https://kubernetes.default.svc
    namespace: default     # or any target namespace for PostgreSQL

  syncPolicy:
    automated:             # Optional: enables auto-sync
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
