apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgvector
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 14.1.2
    helm:
      values: |
        image:
          repository: tensorchord/pgvecto.rs
          tag: latest
        auth:
          username: postgres
          password: immich
          database: immich
        primary:
          persistence:
            existingClaim: pgvector-pvc
            enabled: true
            storageClass: ""
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
