apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgvector-storage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/RJ598/kubecluster  # change this
    targetRevision: HEAD
    path: Application/pervolume  # path to your pv manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
