apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
      - name: home-assistant
        image: ghcr.io/home-assistant/home-assistant:2025.4.3
        ports:
        - containerPort: 8123
        volumeMounts:
        - mountPath: /config
          name: home-assistant-storage
      volumes:
      - name: home-assistant-storage
        persistentVolumeClaim:
          claimName: home-assistant-pvc
