apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-pv
  namespace: home-assistant
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/home-assistant"  # Change as needed
    type: DirectoryOrCreate