apiVersion: v1
kind: Service
metadata:
  name: home-assistant-service
  namespace: home-assistant
spec:
  type: NodePort
  ports:
    - port: 8123
      targetPort: 8123
      nodePort: 30123
  selector:
    app: home-assistant
