apiVersion: v1
kind: Service
metadata:
  name: home-assistant-clusterip
  namespace: home-assistant
spec:
  type: ClusterIP
  ports:
    - port: 8123             # Exposed port (internal access)
      targetPort: 8123        # Container's listening port
      protocol: TCP
  selector:
    app: home-assistant       # Matches the labels in your Deployment
