apiVersion: v1
kind: Service
metadata:
  name: stremio
  namespace: default
spec:
  type: NodePort
  selector:
    app: stremio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 # Stremio container port
      nodePort: 30080   # Ensure it's between 30000-32767