apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgvector-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /mnt/data/pgvector  # Adjust for your node
  persistentVolumeReclaimPolicy: Retain
