apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://fluent.github.io/helm-charts
    chart: fluent-bit
    targetRevision: latest
    helm:
      values: |
        config:
          service:
            flush: 5
            log_level: info
          inputs:
            tail:
              path: /var/log/containers/*.log
              parser: docker
              tag: kube.*
          outputs:
            es:
              match: "*"
              host: elasticsearch.logging.svc.cluster.local
              port: 9200
              logstash_prefix: fluentbit
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
