apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-event-exporter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: kube-event-exporter
    targetRevision: latest
    helm:
      values: |
        config:
          logLevel: debug
          route:
            include:
              - "^.*$"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
