apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zabbix
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://zabbix-community.github.io/helm-zabbix
      chart: zabbix           # correct chart name
      targetRevision: 3.2.0   # latest chart version
      helm:
        releaseName: zabbix
        values: |
          zabbix_image_tag: ubuntu-7.0-latest
          postgresql:
            enabled: true
            auth:
              postgresPassword: zabbix
              password: zabbix
          zabbixServer:
            dbPassword: zabbix
          zabbixWeb:
            dbPassword: zabbix
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
