apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: docker-io-helm-oci
  namespace: argocd
stringData:
  url: oci://ghcr.io/immich-app/immich-charts/immich
  name: immich-charts
  type: helm
  enableOCI: "true"