apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voice-of-pm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/RJ598/kubecluster  # Your Git repo with Kubernetes manifests
      path: Applications/voice-of-pm  # Path to manifests inside the repo
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true        # Removes resources not in Git
      selfHeal: true     # Corrects drift in cluster
      allowEmpty: false
    syncOptions:
      - Validate=false
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
