apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voice-of-pm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/RJ598/voice-of-pm-k8s.git'
    targetRevision: HEAD
    path: .
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true