apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgvector-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 30Gi
