name: cloudflared-argocd
replicas: 2
tunnel: rohan-tunnel
ingress:
- hostname: argo.rohanj.info
  serviceName: argocd-server.argocd.svc.cluster.local
  servicePort: 80
- hostname: web.rohanj.info
  serviceName: nginx-service.default.svc.cluster.local
  servicePort: 80
- hostname: kiali.rohanj.info
  serviceName: kiali.istio-system.svc.cluster.local
  servicePort: 20001

secretName: cloudflared-cred
secrets:
  enabled: false
serviceAccount:
  create: false
warp: false
