name: cloudflared-argocd
replicas: 2
tunnel: a845fc46-3423-43b1-a8b0-be7534914156
ingress:
- hostname: argo.rohanj.info
  serviceName: argocd-server.argocd.svc.cluster.local
  servicePort: 80
- hostname: web.rohanj.info
  serviceName: voice-of-pm.default.svc.cluster.local
  servicePort: 80
- hostname: stream.rohanj.info
  serviceName: stremio
  servicePort: 80
- hostname: ha.rohanj.info
  serviceName: home-assistant-service.home-assistant.svc.cluster.local
  servicePort: 8123
- hostname: za.rohanj.info
  serviceName: zabbix-zabbix-web.observability.svc.cluster.local
  servicePort: 80
  originRequest:
    httpHostHeader: za.rohanj.info
secretName: cloudflared-cred
secrets:
  enabled: false
serviceAccount:
  create: false
warp: false
